rules:
  - id: wp-rest-permission-callback-true-callback
    languages:
      - php
    message: REST routes should not use a permission callback that unconditionally returns true.
    severity: ERROR
    patterns:
      - pattern: |
          register_rest_route(
            ...,
            [
              ...,
              'permission_callback' => function (...) {
                ...
                return true;
              },
              ...,
            ],
            ...
          )
